import { Book, LibraryBook, mainLibrary } from "./library";


export const populate = async () => {

const books : Book[] = [ // generated by GPT model
        { id:"0451524934", title: "1984", author: "George Orwell", publisher: "Secker & Warburg", publish_year: "1949", ISBN_10: "0451524934", language: "English", category: "Fiction", genre: "Dystopian", keywords: "totalitarianism, surveillance" },
        { id:"9780141036144", title: "1984", author: "George Orwell", publisher: "Penguin Books", publish_year: "1950", ISBN_13: "9780141036144", language: "English", genre: "Dystopian" },
        { id:"0743273567", title: "The Great Gatsby", author: "F. Scott Fitzgerald", publisher: "Charles Scribner's Sons", publish_year: "1925", ISBN_10: "0743273567", language: "English", genre: "Tragedy" },
        { id:"9780141182636",title: "The Great Gatsby", author: "F. Scott Fitzgerald", publisher: "Penguin Classics", publish_year: "2000", ISBN_13: "9780141182636", language: "English" },
        { id:"id-1", title: "Moby Dick", author: "Herman Melville", publisher: "Harper & Brothers", publish_year: "1851", genre: "Adventure", keywords: "whale, sea" },
        { id:"9780142437247", title: "Moby Dick", author: "Herman Melville", publisher: "Penguin Classics", publish_year: "2001", ISBN_13: "9780142437247", language: "English", genre: "Adventure" },
        { id:"id-2", title: "To Kill a Mockingbird", author: "Harper Lee", publisher: "J.B. Lippincott & Co.", publish_year: "1960", category: "Fiction", genre: "Southern Gothic", keywords: "racism, justice" },
        { id:"id-3", title: "The Catcher in the Rye", author: "J.D. Salinger", publisher: "Little, Brown and Company", publish_year: "1951", language: "English", genre: "Realism" },
        { id:"9780199535569", title: "Pride and Prejudice", author: "Jane Austen", publish_year: "1813", ISBN_13: "9780199535569", category: "Fiction", genre: "Romance", keywords: "love, society" },
        { id:"9780141439518", title: "Pride and Prejudice", author: "Jane Austen", publisher: "Penguin Books", publish_year: "2003", ISBN_13: "9780141439518", language: "English", genre: "Romance" },
        { id:"id-4", title: "The Hobbit", author: "J.R.R. Tolkien", publisher: "George Allen & Unwin", publish_year: "1937", genre: "Fantasy" },
        { id:"9780261102217", title: "The Hobbit", author: "J.R.R. Tolkien", publisher: "HarperCollins", publish_year: "1999", ISBN_13: "9780261102217", language: "English" },
        { id:"id-5", title: "Brave New World", author: "Aldous Huxley", publisher: "Chatto & Windus", publish_year: "1932", language: "English" },
        { id:"9780060850524", title: "Brave New World", author: "Aldous Huxley", publisher: "Harper Perennial", publish_year: "2006", ISBN_13: "9780060850524", language: "English", genre: "Dystopian" },
        { id:"id-5", title: "The Odyssey", author: "Homer", publisher: "Penguin Classics", publish_year: "1996", language: "Greek", genre: "Mythology", keywords: "epic, journey" },
        { id:"9780199536788", title: "The Odyssey", author: "Homer", publisher: "Oxford University Press", publish_year: "2008", ISBN_13: "9780199536788", genre: "Epic" },
        { id:"id-6", title: "The Road", author: "Cormac McCarthy", publisher: "Alfred A. Knopf", publish_year: "2006", genre: "Post-apocalyptic", keywords: "father, son, survival" },
        { id:"9780307387899", title: "The Road", author: "Cormac McCarthy", publisher: "Vintage", publish_year: "2007", ISBN_13: "9780307387899", language: "English", genre: "Post-apocalyptic" }
    ];

    // Generate over 20 library books from the book list, adding similar titles with different editions
    const libBooks : LibraryBook[] = [
        new LibraryBook("L001", books[0].id),
        new LibraryBook("L002", books[1].id),
        new LibraryBook("L003", books[2].id),
        new LibraryBook("L004", books[3].id),
        new LibraryBook("L005", books[4].id),
        new LibraryBook("L006", books[5].id),
        new LibraryBook("L007", books[6].id),
        new LibraryBook("L008", books[7].id),
        new LibraryBook("L009", books[8].id),
        new LibraryBook("L010", books[9].id),
        
        // Adding more copies with different library IDs for different editions
        new LibraryBook("L011", books[0].id),
        new LibraryBook("L012", books[1].id),
        new LibraryBook("L013", books[2].id),
        new LibraryBook("L014", books[3].id),
        new LibraryBook("L015", books[4].id),
        new LibraryBook("L016", books[5].id),
        new LibraryBook("L017", books[6].id),
        new LibraryBook("L018", books[7].id),
        new LibraryBook("L019", books[8].id),
        new LibraryBook("L020", books[9].id),
        
        // Duplicates with editions, different publishers
        new LibraryBook("L021", books[10].id),
        new LibraryBook("L022", books[11].id),
        new LibraryBook("L023", books[12].id),
        new LibraryBook("L024", books[13].id),
        new LibraryBook("L025", books[14].id),
        new LibraryBook("L026", books[15].id),
        new LibraryBook("L027", books[16].id),
        new LibraryBook("L028", books[17].id),
    ];

    const booksToPurge = await mainLibrary.getAllBookInfos();
    await Promise.all(booksToPurge.map(book => mainLibrary.removeBookInfo(book.id)));
    await Promise.all(books.map(book => mainLibrary.addBookInfo(book)));
    
    mainLibrary.registerBooks(libBooks)
}